### ISSUE TITLE
Adding tab completion and folder lookup

### ISSUE THREAD

**Issue by stared** [al63/SublimeFiles#9]
Do you plan adding tab completion (as it is in Linux/OSX terminal)?
(I don't know if it is possible in Sublime Text 2.)

**Comment by al63** [comment]
Hey there!

I don't think i'll add tab completion anytime soon as i'm not really even sure its possible. I don't know how I could steal tab keystrokes from the "quick panel" in sublime's API that is used to pop up the list of files/directories.

For '~/', the behavior is intended (or rather, it was just implemented that way). It would indeed be really cool to have ~/ straight up list the files or directories though. Once again I'm not sure how we could implement that just because I rely on sublime's "quick panel". I'll probably look into it and play around with it later, but if you want to have a hand at it I encourage you to do so.

**Comment by stared** [comment]
Thanks for a rapid reply.

Now I see that it is a nice hack of the sublime palette search. So I will just adopt (and BTW: some things are actually different, not worse - e.g. it searches whole words, not only the beginnings).
